# Config for BucikTitles

language:
  plugin-prefix: "&f&l[&c&lB&6&lu&e&lc&a&li&b&lk&3&lTitles&f&l]&r "
  title-set: "&aTytuł został pomyślnie ustawiony! Mogą go teraz zobaczyć inni nad twoją głową!"
  title-removed: "&aTytuł został usunięty znad twojej głowy!"
  no-permission: "&cBrak uprawnień!"
  cannot-open-from-console: "&cNie możesz wykonać tego polecenia z konsoli."
  plugin-reloaded: "&aKonfiguracja została przeładowana."
  subcommand-does-not-exist: "&cTa podkomenda nie istnieje."

gui:
  title: "&0>>> &lTYTUŁY &0<<<"
  outline-pane:
    item: BLUE_STAINED_GLASS_PANE
    name: "TestName"
    lore:
      - "TestLore1"
      - "TestLore2"
  clear-titles-button:
    name: "&cUsuń wybrany tytuł"
  previous-page-button:
    name: "&4< &cWróć"
  next-page-button:
    name: "&aDalej &2>"

misc:
  play-sound-after-setting: true
  play-sound-after-clear: true
  clear-title-on-player-quit: false

# INFO: One GUI page can handle up to 28 titles.

titles:
  pages:
    1:
      example:
        title: "&e&o[&7Example&8Title&e&o]&r"
        permission: "example.permission"
        gui-item:
          material: BOOK
          name: "Testowy tytuł"
          amount: 1
          lore:
            - "Testowy lore 1"
            - "Testowy lore 2"
      wzium:
        title: "&e&oSiemanencjusz"
        permission: "example.permission2"
        gui-item:
          material: DIAMOND_SWORD
          name: "Testowy tytuł"
          amount: 1
          lore:
            - "Testowy lore XD"
            - "Testowy lore 2"
    2:
      example:
        title: "&e&o[&7Examplasdsad]&r"
        permission: "example.permission3"
        gui-item:
          material: BAMBOO
          name: "Testasdasdasdytuł"
          amount: 1
          lore:
            - "Test lore 1"
            - "Test lore 2"
      wzium:
        title: "&e&oSiemanencjusz"
        permission: "example.permission4"
        gui-item:
          material: PLAYER_HEAD
          texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2IwM2M0OTg2ODlkNDg2NmRmYTA5MDFhZmNjNmM2NmVmODFhYmUxNTMwZDNlZmI2MGEzMzBiYTlkMjM0YjRlNSJ9fX0="
          name: "Testowy tytuł"
          amount: 1
          lore:
            - "Testowy lore XD"
            - "Testowy lore 2"