# Config for BucikTitles

# Showing title modes:
# above_head
# above_head_chat

options:
  locale: en
  play-sounds: true
  clear-title-on-player-quit: false
  show-title: above_head_chat # In order for this to work, "unlimited-nametag-prefix-suffix-mode" must be enabled in TAB config.yml.
  debug: false

gui:
  title: "&0>>> &lTITLES &0<<<"
  outline-pane:
    item: BLUE_STAINED_GLASS_PANE
    name: "&fPlaceholder"
    lore:
      - "&3Bucik"
      - "&aTitles!"
  clear-titles-button:
    name: "&cRemove the current title"
  previous-page-button:
    name: "&4< &cBack"
  next-page-button:
    name: "&aNext &2>"
