name: BucikTitles
version: 1.1.7
main: pl.workonfire.buciktitles.Main
api-version: 1.13
depend: [TAB]
softdepend: [PlaceholderAPI]
authors: [Buty935]
description: A simple plugin for handling player prefixes
commands:
  titles:
    aliases: [tytuly, buciktitles, prefixes]
