name: BucikTitles
version: 1.0
main: pl.workonfire.buciktitles.Main
api-version: 1.14
load: STARTUP
depend: [TAB]
authors: [Buty935]
description: A simple plugin for showing player titles
commands:
  titles:
    aliases: [tytuly]