name: BucikTitles
version: 1.0.3
main: pl.workonfire.buciktitles.Main
api-version: 1.14
depend: [TAB]
authors: [Buty935]
description: A simple plugin for showing player titles
commands:
  titles:
    aliases: [tytuly, buciktitles]